### ISSUE TITLE
GitLab Paginated Pull Requests Duplicated

### ISSUE THREAD

**Issue by mattBrzezinski** [JuliaWeb/GitForge.jl#24]
```julia
using GitForge

lab_token = GitForge.GitLab.PersonalAccessToken("{REDACTED}")
lab_api = GitForge.GitLab.GitLabAPI(token=lab_token, url="https://{REDACTED}/api/v4")
repo =  get_repo(lab_api, "{REDACTED_OWNER}", "{REDACTED_PROJECT}")

prs = get_pull_requests(lab_api, repo.val.id; state="opened", per_page=100, page_limit=100)
length(GitForge.value(prs))  # 7

prs = @paginate get_pull_requests(lab_api, repo.val.id; state="opened", per_page=100, page_limit=100)
arr = []

for x in prs
    push!(arr, x)
end

length(arr)  # 14
```

I'm really not sure what's going on here doing `arr[1] == arr[8]` returns false, but looking at the values they're all the same. I haven't come across this w/ GitHub pagination of pull requests.

**Comment by mattBrzezinski** [comment]
Tried adding in `@auto_hash_equals` but it doesn't play nice w/ the `@json` macro, removing the `@json` macro breaks the call.

**Comment by mattBrzezinski** [comment]
Adding in the following functionality lets you compare nicely, taken from [Distributions.jl](https://github.com/JuliaStats/Distributions.jl/blob/2af8703e36bef543664700ae04aaa279e4ecf958/src/common.jl#L75)

```julia
for func in (:(==), :isequal, :isapprox)
    @eval function Base.$func(s1::A, s2::B; kwargs...) where {A<:GitLab.MergeRequest, B<:GitLab.MergeRequest}
        nameof(A) === nameof(B) || return false
        fields = fieldnames(A)
        fields === fieldnames(B) || return false

        for f in fields
            isdefined(s1, f) && isdefined(s2, f) || return false
            $func(getfield(s1, f), getfield(s2, f); kwargs...) || return false
        end

        return true
    end
end
```

**Comment by mattBrzezinski** [comment]
Doesn't resolve the issue of why iterating over a paginated request from GitLab returns duplicates, but gives a workaround I suppose.

```julia
julia> for x in prs
         println(x.id)
         end
┌ Warning: Parsing rate limit headers failed
└ @ GitForge ~/.julia/dev/GitForge.jl/src/ratelimits.jl:39
14472
7352
6634
6626
6622
6435
6433
┌ Warning: Parsing rate limit headers failed
└ @ GitForge ~/.julia/dev/GitForge.jl/src/ratelimits.jl:39
14472
7352
6634
6626
6622
6435
6433
```

**Comment by christopher-dG** [comment]
Yeah, the pagination definitely needs an overhaul. I'll have a look soon (I'm currently working on other stuff in this package).

**Comment by mattBrzezinski** [comment]
> Yeah, the pagination definitely needs an overhaul. I'll have a look soon (I'm currently working on other stuff in this package).

:+1: Sounds good, the comparison code above I have provides a work around to remove duplicates so it's no big deal.

**Comment by mattBrzezinski** [comment]
With the release of `v0.2` this issue is resolved.

```julia
julia> prs = GitForge.paginate(GitLab.get_pull_requests, lab_api, repo[1].id; state="opened")
julia> p = collect(prs)
julia> allunique(p)
true
```
