### ISSUE TITLE
Rate Limit Warning Somewhat Noisy

### ISSUE THREAD

**Issue by fchorney** [JuliaWeb/GitForge.jl#28]
Im guessing GitLab doesn't send these rate limit headers, and seeing this warning (https://github.com/JuliaWeb/GitForge.jl/blob/master/src/ratelimits.jl#L31) for every request seems somewhat misleading and noisy. 

Is there a better solution?

**Comment by christopher-dG** [comment]
Self-hosted GitLab has no rate limits (or they can be disabled at least), the community version does. `GitLabAPI` has a `has_rate_limits` keyword to disable the checks and subsequent warnings.

**Comment by fchorney** [comment]
oh interesting, thanks for the info! Guess I can probably close this then
