### ISSUE TITLE
Update for `HTTP.jl` 1.0 and release a new version

### ISSUE THREAD

**Issue by giordano** [JuliaWeb/GitForge.jl#37]
This package still requires HTTP 0.8 or 0.9, holding back some dependencies.  I tried to allow HTTP.jl 1.0 in https://github.com/JuliaWeb/GitForge.jl/blob/9f7a48c9545048f6c0d3c82370c1f245b623a2dd/Project.toml#L12 but I got tests failures, which are out of my depth (and time availablity).  CC: @quinnj.

**Comment by quinnj** [comment]
Implemented in #39; will do a 0.3.0 release soonish
